version: '3.8'

networks:
  licitracker-net:
    name: licitracker-net
    driver: bridge

services:
  licitracker-db:
    image: postgres:16
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - licitracker-pgdata:/var/lib/postgresql/data
    networks:
      - licitracker-net

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - licitracker-db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: "8080"
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - licitracker-net

volumes:
  licitracker-pgdata: